default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  encoding: utf8
  database: local
  username: root
  password: root
  host: mysql

test:
  <<: *default

production:
  <<: *default
